- name: action-toolbelt
  referenceId: 73SEVYK2
  build:
    provider: dkcicd
    pipelines:
      - name: node-ci-v2
        parameters:
          sonarProjectName: action-toolbelt
          nodeVersion: 20-bookworm
          nodeCommands: [] 
          skipInstall: true
        runtime:
          architecture: amd64
        when:
          - event: pull_request
            source: branch
          - event: push
            source: branch
            regex: main
      - name: techdocs-v1
        parameters:
          entityReference: default/component/action-toolbelt
          sourceDir: ./
        when:
          - event: push
            source: branch
            regex: main
            path:
              - "docs/**"
              - README.md
              - .vtex/deployment.yaml
