- name: action-toolbelt
  build:
    provider: dkcicd
    pipelines:
      - name: techdocs-v1
        parameters:
          entityReference: default/component/action-toolbelt
          sourceDir: ./
        when:
          - event: push
            source: branch
            regex: main
            path:
              - "docs/**"
              - README.md
              - .vtex/deployment.yaml